config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  scope module: :public do
    root "homes#top"

    resource :user, only: [:update] do
      member do
        get "confirm"
        patch "withdraw"
        get "bookmarks"
      end
      # deviseのルーティングと被るため、informationを追加
      get "information/edit", to: "users#edit"
      get "mypage", action: :show
    end

    devise_scope :user do
      # 新規登録失敗後のリダイレクトのエラーを防ぐルーティング
      get "/users", to: "registrations#new"
      post "/users/guest_login", to: "users#guest_login"
    end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }

    resources :recipes do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      collection do
        get "search"
      end
    end

    # タグ検索用ルーティング
    get "tags/:tag_id/recipes", to: "recipes#tag_search", as: "tag_recipes"

    resources :chatbots, only: [:create]
  end

  get "/admin", to: "admin/homes#top"

  devise_for :admins, controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :content, presence: true, length: { maximum: 300 }
  validates :score, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @comments = Comment.includes(:user, :recipe).page(params[:page]).per(12)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to admin_comments_path
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<h1>コメント管理画面</h1>
<%= link_to "ユーザー管理画面はこちら", admin_users_path %><br>
<%= link_to "タグ管理画面はこちら", admin_tags_path, class: "d-block my-2" %>
<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>コメントしたレシピ</th>
        <th>ユーザーネーム</th>
        <th>コメント内容</th>
        <th>投稿日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.recipe.title %></td>
          <td><%= comment.user.name %></td>
          <td><%= comment.content %></td>
          <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td>
            <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: "#{comment.content}を削除しますか？"}, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @comments %>
  </div>
</div>