config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  scope module: :public do
    root "homes#top"

    resource :user, only: [:update] do
      member do
        get "confirm"
        patch "withdraw"
        get "bookmarks"
      end
      # deviseのルーティングと被るため、informationを追加
      get "information/edit", to: "users#edit"
      get "mypage", action: :show
    end

    devise_scope :user do
      # 新規登録失敗後のリダイレクトのエラーを防ぐルーティング
      get "/users", to: "registrations#new"
      post "/users/guest_login", to: "users#guest_login"
    end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }

    resources :recipes do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      collection do
        get "search"
      end
    end

    # タグ検索用ルーティング
    get "tags/:tag_id/recipes", to: "recipes#tag_search", as: "tag_recipes"

    resources :chatbots, only: [:create]
  end

  get "/admin", to: "admin/homes#top"

  devise_for :admins, controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  has_many :having_recipes, through: :bookmarks, source: :recipe

  scope :popular, -> {
    select("tags.*, COUNT(recipes.id) as recipes_count")
    .joins(:recipes)
    .group("tags.id")
    .order("recipes_count DESC")
    .limit(10)
  }
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tags = Tag.page(params[:page]).per(12)
    @tag = Tag.new
  end

  def new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end


  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/index.html.erb
<h1>タグ管理画面</h1>
<%= link_to "コメント管理画面はこちら", admin_comments_path %><br>
<%= link_to "ユーザー管理画面はこちら", admin_users_path, class: "d-block my-2" %>

<div class="row">
  <div class="col-md-6">
    <h2 class="my-2">タグ一覧</h2>

    <div class="table-responsive">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>タグ名</th>
            <th>使用数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td><%= tag.name %></td>
              <td><%= tag.recipes.count %></td>
              <td>
                <%= link_to admin_tag_path(tag), method: :delete, data: { confirm: "本当に削除しますか？"} do %>
                  <i class="fa fa-trash text-danger"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @tags %>
      </div>
    </div>
  </div>

  <!-- Add New Tag Section -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h2>新しいタグの作成</h2>
      </div>
      <div class="card-body">
        <%= form_with model: [:admin, @tag], class: 'new-tag' do |form| %>
          <div class="form-group">
            <%= form.label :name, "名前", class: 'form-label' %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group text-center">
            <%= form.submit "タグを作成する", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tags/new.html.erb
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-header">
          <h2 class="text-center">新しいタグの作成</h2>
        </div>
        <div class="card-body">
          <%= form_with model: [:admin, @tag], class: 'new-tag' do |form| %>
            <div class="form-group">
              <%= form.label :name, class: 'form-label' %>
              <%= form.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group text-center">
              <%= form.submit "タグを作成する", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="text-center mt-3">
        <%= link_to 'タグ一覧に戻る', admin_tags_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>