config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  scope module: :public do
    root "homes#top"

    resource :user, only: [:update] do
      member do
        get "confirm"
        patch "withdraw"
        get "bookmarks"
      end
      # deviseのルーティングと被るため、informationを追加
      get "information/edit", to: "users#edit"
      get "mypage", action: :show
    end

    devise_scope :user do
      # 新規登録失敗後のリダイレクトのエラーを防ぐルーティング
      get "/users", to: "registrations#new"
      post "/users/guest_login", to: "users#guest_login"
    end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }

    resources :recipes do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      collection do
        get "search"
      end
    end

    # タグ検索用ルーティング
    get "tags/:tag_id/recipes", to: "recipes#tag_search", as: "tag_recipes"

    resources :chatbots, only: [:create]
  end

  get "/admin", to: "admin/homes#top"

  devise_for :admins, controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarking_recipes, through: :bookmarks, source: :recipe

  has_one_attached :image
  def get_image
    if image.attached?
      image
    else
      ActiveStorage::Blob.create_and_upload!(io: File.open(Rails.root.join("app", "assets", "images", "no_image.jpg")), filename: "no_image.jpg")
    end
  end


  # そのレシピをユーザーがブックマークしているかどうか判断するメソッド
  def bookmarking?(recipe)
    bookmarking_recipes.include?(recipe)
  end
  # ゲストログイン用のメソッド
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(12)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :index
    end
  end

  private
    def user_params
      params.require(:user).permit(:is_deleted)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<h1>ユーザー管理画面</h1>
<%= link_to "コメント管理画面はこちら", admin_comments_path %><br>
<%= link_to "タグ管理画面はこちら", admin_tags_path, class: "d-block my-2" %>
<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>ユーザーネーム</th>
        <th>Email</th>
        <th>ユーザーステータス</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.is_deleted ? '<span class="text-danger">退会済み</span>'.html_safe : '<span class="text-success">アクティブ</span>'.html_safe %></td>
          <td>
            <%= form_with model: [:admin, user],url: admin_user_path(user),  method: :patch do |f| %>
              <%= f.hidden_field :is_deleted, value: !user.is_deleted %>
              <%= f.submit "更新する", id: "update_user_#{user.id}" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @users %>
  </div>
</div>