config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "homes/top"
  end
  scope module: :public do
    root "homes#top"

    resource :user, only: [:update] do
      member do
        get "confirm"
        patch "withdraw"
        get "bookmarks"
      end
      # deviseのルーティングと被るため、informationを追加
      get "information/edit", to: "users#edit"
      get "mypage", action: :show
    end

    devise_scope :user do
      # 新規登録失敗後のリダイレクトのエラーを防ぐルーティング
      get "/users", to: "registrations#new"
      post "/users/guest_login", to: "users#guest_login"
    end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }

    resources :recipes do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      collection do
        get "search"
      end
    end

    # タグ検索用ルーティング
    get "tags/:tag_id/recipes", to: "recipes#tag_search", as: "tag_recipes"

    resources :chatbots, only: [:create]
  end

  get "/admin", to: "admin/homes#top"

  devise_for :admins, controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :users, only: [:index, :update]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :user_id, scope: :recipe_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :content, presence: true, length: { maximum: 300 }
  validates :score, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true
  validates :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true

  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :recipe_tags
  has_many :tags, through: :recipe_tags
  has_many :ingredients
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  has_one_attached :image

  def get_image
    if image.attached?
      image
    end
  end
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag

  validates_uniqueness_of :tag_id, scope: :recipe_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  has_many :having_recipes, through: :bookmarks, source: :recipe

  scope :popular, -> {
    select("tags.*, COUNT(recipes.id) as recipes_count")
    .joins(:recipes)
    .group("tags.id")
    .order("recipes_count DESC")
    .limit(10)
  }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarking_recipes, through: :bookmarks, source: :recipe

  has_one_attached :image
  def get_image
    if image.attached?
      image
    else
      ActiveStorage::Blob.create_and_upload!(io: File.open(Rails.root.join("app", "assets", "images", "no_image.jpg")), filename: "no_image.jpg")
    end
  end


  # そのレシピをユーザーがブックマークしているかどうか判断するメソッド
  def bookmarking?(recipe)
    bookmarking_recipes.include?(recipe)
  end
  # ゲストログイン用のメソッド
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @comments = Comment.includes(:user, :recipe).page(params[:page]).per(12)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to admin_comments_path
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tags = Tag.page(params[:page]).per(12)
    @tag = Tag.new
  end

  def new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end


  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(12)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :index
    end
  end

  private
    def user_params
      params.require(:user).permit(:is_deleted)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  protected
    def admin_url
      request.fullpath.include?("/admin")
    end

    def after_sign_in_path_for(resource)
      if resource.is_a?(Admin)
        admin_path
      else
        mypage_user_path
      end
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message_for(field, model)
    if model.errors[field].any?
      tag.div class: "invalid-feedback d-block" do
        model.errors[field].join(", ")
      end
    end
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 footer-custom-color border-top">
  <div class="container d-flex justify-content-between">
    <span class="text-muted">Copyright © 猿レシピ 2023</span>
    <ul class="nav flex-column">
      <% unless admin_signed_in? %>
        <%= link_to 'レシピ一覧', recipes_path, class: 'nav-link text-dark' %>
        <%= link_to '新規登録', new_user_registration_path, class: 'nav-link text-dark' %>
        <%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-dark' %>
        <%= link_to '管理者の方はこちら', new_admin_session_path, class: 'nav-link text-dark' %>
        <%= link_to '退会はこちら', confirm_user_path, class: 'nav-link text-dark' %>
      <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="pb-3">

  <nav class="navbar navbar-expand-lg navbar-light nav-custom-color border-bottom">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "monkey.png", size: "50x50", class: "align-middle" %>
      <h1 id="logo" class="align-middle">猿レシピ</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% unless admin_signed_in? %>
          <%= form_with(url: search_recipes_path, method: :get, local: true, html: {class: "form-inline my-2 my-lg-0"}) do |form| %>
            <%= form.text_field :word, placeholder: "レシピを検索する", class: "form-control mr-sm-2" %>
            <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "レシピ作成", new_recipe_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "レシピ一覧", recipes_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to mypage_user_path, class: 'nav-link' do %>
            <i class="fa-regular fa-user mx-1"></i>プロフィール
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="fa-solid fa-arrow-right-from-bracket mx-1"></i>ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="fa-solid fa-arrow-right-from-bracket mx-1"></i>管理者ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link' do %>
              <i class="fa-solid fa-user mx-1"></i>新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_guest_login_path, method: :post, class: 'nav-link' do %>
              <i class="fa-solid fa-person-circle-question mx-1"></i>ゲストログイン
            <% end %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link' do %>
              <i class="fa-solid fa-arrow-right-to-bracket mx-1"></i>ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>猿レシピ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    
    <script src="https://kit.fontawesome.com/c535638148.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Subrayada&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>

    <main class="min-vh-100">
    <div class="container">
      <div class="d-flex justify-content-center">
        <% if notice %>
          <div class="alert alert-dark mb-3 d-inline-block" role="alert">
            <%= notice %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>